version: "2.0"
language: zh
pipeline:
  - name: "SpacyNLP"
    model: "zh_core_web_md"
  - name: SpacyTokenizer
  - name: RegexFeaturizer
    "case_sensitive": False
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: SpacyFeaturizer
  - name: SpacyEntityExtractor
  - name: SklearnIntentClassifier
  - name: DIETClassifier
    epochs: 500
    batch_size: 256
    scale_loss: false
    drop_rate_attention: 0.1
    drop_rate: 0.1
  - name: RegexEntityExtractor
    case_sensitive: False
    use_lookup_tables: True  
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 500
    batch_size: 256
    drop_rate_attention: 0.1
    drop_rate: 0.1
    scale_loss: false
policies:
  - name: AugmentedMemoizationPolicy
  - name: TEDPolicy
    epochs: 300
  - name: "RulePolicy"
    core_fallback_threshold: 0.3
    core_fallback_action_name: utter_notknow
    enable_fallback_prediction: false
    restrict_rules: true
    check_for_contradictions: true
